name: repo_viewer
description: Github repositories viewer application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.1
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  dio: ^5.0.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.0
  freezed_annotation: ^2.2.0
  webview_flutter: ^4.0.6
  flash: ^2.0.5+1
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lint: ^2.0.1
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
